### ISSUE TITLE
ExceptionHandling block not generating log files.

### ISSUE THREAD

**Issue by nipanesanjay** [Chavoshi/EnterpriseLibrary.NetCore#20] opened 2018-08-09 13:20 UTC
Hi,
I am using Exception Handling and Logging .NET Core block for automatically logging the exceptions when they occur in different layers of my .NET Core app. 

I have created .NET COre library in which all exception handlers are written to server for each layer.
And then using this library in .Net Core Web API. App.config file has been placed containing all logging section details in Web API. While debugging the code, I can see configuration file gets read also properly. But when any exception gets thrown then while logging exception through library using 'ExceptionPolicy.HandleException(ex, policy_name)' it gives message as 'Exception User-Unhandled'.

In bin folder, I can see _log_ folder gets generated but no log file.
Please let me know if I am missing anything here.

Regards
Sanjay

**Comment by Chavoshi** [comment] 2018-08-10 02:00
Hi Sanjay,
It is impossible to tell what is the issue blindly without any code, if it works for you share part of your code with me then I can tell you what exactly is happening.

**Comment by nipanesanjay** [comment] 2018-08-10 08:17
Thanks Chavoshi for quick reply.

I have created one .NET Standard based class library - CommonExceptionhandlingAndLogging. In that I have defined Exception Handler classes to handle exceptions at each layer - Service, Business and Data Access Layer.

In 'HandleException' method of these classes I have following code line - 
1) rethrow = ExceptionPolicy.HandleException(ex, "ServiceLayerPolicy");

The policies are configured in app.config places in .NET Core Web API. See snapshot of app.config below:
![image](https://user-images.githubusercontent.com/38030689/43946614-00c7eaea-9c86-11e8-8321-e6b4e1f335b5.png)

When I invoke the Service layer exception handler from Web API controller,
2) bool rethrow = Common.ExceptionHandling.ServiceExceptionHandler.HandleException(ref ex);, execution comes to the code line 1) of class library as mentioned above. But then gives exception as 'Exception User-unhandled'.

I am using all .NET Core based NuGet packages for EL.

Please let me know if you can provide some solution on the above shared code blocks.

**Comment by nipanesanjay** [comment] 2018-08-13 09:47
Hi, while going through further blogs, I found that one of the blog is saying flat file trace listener is missing in EL of .NET Core. Is this correct?

https://forums.asp.net/t/2138534.aspx?will+net+core+2+0+support+enterprise+library+6+If+so+any+documentation+available+%27

**Comment by nipanesanjay** [comment] 2018-08-15 08:01
Hi, can I get any support on this issue.,

**Comment by moein-shafiei** [comment] 2018-08-21 02:52
Hi, Sorry for late reply. I've been pretty busy these days.
I reproduced the issue and find the problem in Flush method of TextWriterTraceListener which is in .net core. This class does not work properly with just passing the name of log file in .net core however it works the same way in .net. As a result FlatFileTraceListener works properly in .net core but not in .net core.
On the other hand it works in .net core if a stream pass instead of name of file. As a result I will try to change the way that initialize FlatFileTraceListener using a stream.

**Comment by nipanesanjay** [comment] 2018-08-22 09:44
Thanks Moein for the updates.
Let us know by when the corrected version will be available.

**Comment by nipanesanjay** [comment] 2018-08-29 13:37
Hi Moein, any updates on this

**Comment by ademgashi** [comment] 2018-09-18 08:51
Hi @moein-shafiei @Chavoshi I hope you are well with everything. Any news on the TextWriterTraceListener  /FlatFileTraceListener  issue.

**Comment by Chavoshi** [comment] 2018-09-18 09:37
Hi Adem,
Sorry for the delay to fixing the issue.
Actually the issue is fixed and we are finalizing the cross-platform packages to make them ready by end of September.
Just for your information, this repository will be deprecated after the new release this is the new home of EntLib: https://github.com/EnterpriseLibrary/

**Comment by Chavoshi** [comment] 2018-09-18 15:53
No problem buddy.
It's been fixed but not committed yet. The changes are a lot ant it's not easy to stage that part only.

**Comment by ademgashi** [comment] 2018-09-18 16:03
fair enough, I can't wait to test it... kudos for the hard work we really
appreciate it, cheers

Adem Gashi
T: +377 44 937 300

[image: LinkedIn] <http://www.linkedin.com/in/ademg>

**Comment by Chavoshi** [comment] 2018-10-03 08:12
Hi Adam,
Sorry for the delay to update the packages, I will release them by this weekend.

Regards,

**Comment by Chavoshi** [comment] 2018-10-03 08:13
Sorry for the delay to update the packages, I will release them by early next week.

Regards,
@ademgashi

**Comment by ghd258** [comment] 2018-10-18 03:09
update nuget

**Comment by tpechat** [comment] 2019-01-16 15:08
When I am reading this thread.. I am getting scaried more and more to use such DLLs...

**Closed** 2019-01-16 20:32 UTC

**Comment by Chavoshi** [comment] 2019-01-16 20:44
@tpechat 
This repository is deprecated and moved here: https://github.com/EnterpriseLibrary/
also an RC version of some blocks are already available and they will be released by March.
