### ISSUE TITLE
DAAB: DeriveParameters

### ISSUE THREAD

**Issue by jrocha** [Chavoshi/EnterpriseLibrary.NetCore#23] opened 2018-10-09 00:42 UTC
Just tried this lib today and found that DeriveParameters method is implemented to throw NotSupportedException. Is there a particular reason for that?

**Comment by jrocha** [comment] 2018-10-09 00:51
I guess it was that way because System.Data.SqlClient referenced by this project did not have SqlCommandBuilder. The newer version has it.

**Comment by jrocha** [comment] 2018-10-09 01:19
Just added a [PR](https://github.com/Chavoshi/EnterpriseLibrary.NetCore/pull/24) that solved this issue.

**Comment by moein-shafiei** [comment] 2018-10-15 23:02
Hi @jrocha , sorry for delay.
I committed your [PR](https://github.com/Chavoshi/EnterpriseLibrary.NetCore/pull/24)
I will start furthur investigations

**Comment by ghd258** [comment] 2018-10-18 03:08
update nuget

**Comment by memark** [comment] 2019-02-02 08:48
@moein-shafiei Was this fixed? Trying the latest version (6.0.1313) and getting this:

> System.NotSupportedException: Parameter discovery is not supported for connections using GenericDatabase. You must specify the parameters explicitly, or configure the connection to use a type deriving from Database that supports parameter discovery.
>    at Microsoft.Practices.EnterpriseLibrary.Data.Sql.SqlDatabase.DeriveParameters(DbCommand discoveryCommand)

I can provide you with a minimal test case if that helps!

**Comment by moein-shafiei** [comment] 2019-02-04 08:16
@memark
Yes please provide your test case so I can reproduce the issue. Thank you

**Comment by memark** [comment] 2019-02-06 06:31
@moein-shafiei Here is a minimal repro
https://github.com/memark/EntLibTest

You can change the connection string in the Config class. I have reproduced this on both SQL Azure and SQL Local DB.

There are four projects. The _EntLib_ one runs fine, the others (_EntLibNetCore_) all fail. (I tried different versions and platforms just to eliminate that as the cause.)

**Comment by moein-shafiei** [comment] 2019-02-10 12:31
Hi @memark 
This issue is already resolved in RC version -> 6.1.10-rc

**Comment by memark** [comment] 2019-02-10 19:47
@moein-shafiei Thank you, it is indeed fixed!

**Closed** 2019-02-10 22:57 UTC
